In [1]:
import torch
if torch.cuda.is_available():
    device = torch.device("cuda")
    print('There are %d GPU(s) available.' % torch.cuda.device_count())
    print('We will use the GPU:', torch.cuda.get_device_name(0))
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")


There are 1 GPU(s) available.
We will use the GPU: NVIDIA GeForce RTX 4090


In [2]:
import pandas as pd
path = '/root/data/'
comments = pd.read_csv(path + 'Train.csv',encoding='gb18030')
comments_Labels = comments['Labels'].map(lambda x:x.replace("[","").replace("]","").replace("'","").replace('"','')).replace(" ","").str.split(', ', expand=True)
comments_Labels = comments_Labels.stack().reset_index(level=1, drop=True).rename('Labels')
comments = comments.drop(['Labels'], axis=1).join(comments_Labels)
comments = comments.dropna()
moods = {'Love':0, 'Sorrow':1, 'Hate':1, 'Anxiety':2, 'Surprise':3, 'Expect':4, 'Joy':5, 'Anger':6}

print('文本数量（总体）：%d' % comments.shape[0])
for label, mood in moods.items(): 
    print('文本数量（{}）：{}'.format(mood,  comments[comments.Labels==label].shape[0]))

comments.Labels = comments.Labels.map(moods)

文本数量（总体）：39105
文本数量（0）：10225
文本数量（1）：6760
文本数量（1）：2849
文本数量（2）：7877
文本数量（3）：902
文本数量（4）：3695
文本数量（5）：5080
文本数量（6）：1717


In [3]:
import pandas as pd
path = '/root/data/'
train = pd.read_csv(path + 'Train.csv',encoding='gb18030')
train

ID                                               Text  \
0          1  她们 都 睡 蹑手蹑脚 摸黑 上 床 凑 上 去 想 亲 嫣 一下 她 突然 一个 转身 小...   
1          2                                       现在 好 终于 如愿以偿   
2          3  感受 着 小手 温度 享受 着 这份 她 对 我的 依恋 生怕 动 一下 会 让 她 小手 ...   
3          4  望 一眼 背 身 而 卧 妻 如果 她 知道 我的 想法 一定 又 会 那 句 ： 切 又 ...   
4          5  眼睛 逐渐 适应 周围 黑暗 借 着 床头 热 奶 器 上 桔红色 指示灯 微弱 光线 慢慢...   
...      ...                                                ...   
25995  25996                宗林 生活 不会 停止 思想 上 不 会 停止 创新 上 不 会 停止   
25996  25997  开头 他 拿 来 写的 散文 读 刮目相看 还 挑选 篇 刊发 美文 杂志 上 不久 他 又...   
25997  25998                          宗林 一个 好 男人 但 好 男人 也 不幸 遭遇   
25998  25999  本来 他 美丽 贤惠 妻子 一个 温暖 可意 家庭 谁 也 没 想到 妻子 患 绝症 竟 于...   
25999  26000                           宗林 对 妻子 守护 和 送别 感动 许多 朋友   

                           Labels  
0                 ['Love', 'Joy']  
1                         ['Joy']  
2      ['Love', 'Joy', 'Anxiety']  
3             ['Love', 'Anxiety']  
4                 ['Love', 'Joy']  
...                           ...  
25995          ['Love', 'Expect']  
25996                    ['Love']  
25997                  ['Sorrow']  
25998                  ['Sorrow']  
25999          ['Love', 'Sorrow']  

[26000 rows x 3 columns]

In [42]:
import pandas as pd
path = '/root/data/'
test = pd.read_csv(path + 'test.csv',encoding='gb18030')
test

ID                                               Text
0        1                                 天 哪 她 还 真 以为 她 名画家
1        2    真 朋友 无功 利 心 真心 相待 ； 假 朋友 表面 上 逢迎 拍马 暗地里 下绊 子 使坏
2        3                              真的 好 累 好 累 想 休息 写下 文字
3        4                                 湿淋淋 头发 隔 着 毛衣 凉 背心
4        5                                            我不 高手 呦
...    ...                                                ...
6148  6149  再说 拐弯 让 直行 次 右 拐 同方向 直行 车 没有 走 完 我在 等待 后面 车 就 ...
6149  6150                                   这才 一个 学生 应有 面容 呀
6150  6151                        坐下 随着 这 声 命令 同学 们 七零八落 地 坐下
6151  6152  又 周末 去 城内 四 府 街 陈 老师 家里 送 代购 几 本 书 蒙 他 厚爱 再 赠 ...
6152  6153                               刚 开学 一星期 嗓子 就 已经 坏 掉

[6153 rows x 2 columns]

In [43]:
test = test.dropna()

In [4]:
train['Labels'] = train['Labels'].apply(eval)
train = train.join(train['Labels'].str.join('|').str.get_dummies())
train = train.drop('Labels', axis=1)
train

ID                                               Text  Anger  \
0          1  她们 都 睡 蹑手蹑脚 摸黑 上 床 凑 上 去 想 亲 嫣 一下 她 突然 一个 转身 小...      0   
1          2                                       现在 好 终于 如愿以偿      0   
2          3  感受 着 小手 温度 享受 着 这份 她 对 我的 依恋 生怕 动 一下 会 让 她 小手 ...      0   
3          4  望 一眼 背 身 而 卧 妻 如果 她 知道 我的 想法 一定 又 会 那 句 ： 切 又 ...      0   
4          5  眼睛 逐渐 适应 周围 黑暗 借 着 床头 热 奶 器 上 桔红色 指示灯 微弱 光线 慢慢...      0   
...      ...                                                ...    ...   
25995  25996                宗林 生活 不会 停止 思想 上 不 会 停止 创新 上 不 会 停止      0   
25996  25997  开头 他 拿 来 写的 散文 读 刮目相看 还 挑选 篇 刊发 美文 杂志 上 不久 他 又...      0   
25997  25998                          宗林 一个 好 男人 但 好 男人 也 不幸 遭遇      0   
25998  25999  本来 他 美丽 贤惠 妻子 一个 温暖 可意 家庭 谁 也 没 想到 妻子 患 绝症 竟 于...      0   
25999  26000                           宗林 对 妻子 守护 和 送别 感动 许多 朋友      0   

       Anxiety  Expect  Hate  Joy  Love  Sorrow  Surprise  
0            0       0     0    1     1       0         0  
1            0       0     0    1     0       0         0  
2            1       0     0    1     1       0         0  
3            1       0     0    0     1       0         0  
4            0       0     0    1     1       0         0  
...        ...     ...   ...  ...   ...     ...       ...  
25995        0       1     0    0     1       0         0  
25996        0       0     0    0     1       0         0  
25997        0       0     0    0     0       1         0  
25998        0       0     0    0     0       1         0  
25999        0       0     0    0     1       1         0  

[26000 rows x 10 columns]

In [5]:
train = train.dropna()

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26000 entries, 0 to 25999
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   ID        26000 non-null  int64 
 1   Text      26000 non-null  object
 2   Anger     26000 non-null  int64 
 3   Anxiety   26000 non-null  int64 
 4   Expect    26000 non-null  int64 
 5   Hate      26000 non-null  int64 
 6   Joy       26000 non-null  int64 
 7   Love      26000 non-null  int64 
 8   Sorrow    26000 non-null  int64 
 9   Surprise  26000 non-null  int64 
dtypes: int64(9), object(1)
memory usage: 2.2+ MB


In [7]:
len(train)

26000

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.offline as pyo
import plotly.graph_objects as go
import re
from wordcloud import WordCloud, STOPWORDS

import torch
from torch.utils.data import DataLoader, TensorDataset
from transformers import BertTokenizer, BertForSequenceClassification, AdamW
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score

import os
import zipfile
import warnings
warnings.filterwarnings('ignore')

In [9]:
def clean_text(text):
    # Remove HTML tags
    text = re.sub(r'<[^>]+>', '', text)

    # Remove web links
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)

    # Remove special characters, punctuation marks, and numbers
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # Insert spaces between certain patterns (e.g., "ie", "eg")
    text = re.sub(r'(\s)([iI][eE]|[eE][gG])(\s)', r' \2 ', text)

    # Remove extra white spaces
    text = " ".join(text.split())

    return text.lower()

# Example usage with the provided text
texts = [
    "\nMore\nI can't make any real suggestions on improvement - I wondered if the section statistics should be later on, or a subsection of 'types of accidents'  -I think the references may need tidying so that they are all in the exact same format ie date format etc I can do that later on, if no-one else does first - if you have any preferences for formatting style on references or want to do it yourself please let me know.\n\nThere appears to be a backlog on articles for review so I guess there may be a delay until a reviewer turns up. It's listed in the relevant form eg Wikipedia:Good_article_nominations#Transport"
]

cleaned_texts = [clean_text(text) for text in texts]
print(cleaned_texts)

['more i can t make any real suggestions on improvement i wondered if the section statistics should be later on or a subsection of types of accidents i think the references may need tidying so that they are all in the exact same format ie date format etc i can do that later on if no one else does first if you have any preferences for formatting style on references or want to do it yourself please let me know there appears to be a backlog on articles for review so i guess there may be a delay until a reviewer turns up it s listed in the relevant form eg wikipedia good article nominations transport']


In [10]:
target_labels= [col for col in train.columns if train[col].dtypes == 'int64' and train[col].name!='ID']
target_labels

['Anger', 'Anxiety', 'Expect', 'Hate', 'Joy', 'Love', 'Sorrow', 'Surprise']

In [11]:
# Function to generate word cloud
def generate_wordcloud(text,Title):
    wordcloud = WordCloud(width=800, height=400,stopwords=set(STOPWORDS), background_color='black').generate(text)
    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis("off")
    plt.title(Title)
    plt.show()

In [13]:
comments=train['Text'].to_list()
comments[:5]

['她们 都 睡 蹑手蹑脚 摸黑 上 床 凑 上 去 想 亲 嫣 一下 她 突然 一个 转身 小手 啪 地 搭 我的 脸颊 上 我便 被 施 魔法 似地 定 住 每次 抱 着 嫣 时候 总想 让 她 小手 搂 着 我的 脖子 可 她 总是 不肯 她 只 小手 指挥 着 我的 方向 指 着 她 感 兴趣 东西 一刻 也 不肯 停 闲',
 '现在 好 终于 如愿以偿',
 '感受 着 小手 温度 享受 着 这份 她 对 我的 依恋 生怕 动 一下 会 让 她 小手 离 而 去',
 '望 一眼 背 身 而 卧 妻 如果 她 知道 我的 想法 一定 又 会 那 句 ： 切 又 自作 多 情',
 '眼睛 逐渐 适应 周围 黑暗 借 着 床头 热 奶 器 上 桔红色 指示灯 微弱 光线 慢慢 能 看见 她们 轮廓 能 听见 她们 呼吸 天 疲惫 瞬间 不再 难得 一刻 清静']

In [44]:
comments_test=test['Text'].to_list()
comments_test[:5]

['天 哪 她 还 真 以为 她 名画家',
 '真 朋友 无功 利 心 真心 相待 ； 假 朋友 表面 上 逢迎 拍马 暗地里 下绊 子 使坏',
 '真的 好 累 好 累 想 休息 写下 文字',
 '湿淋淋 头发 隔 着 毛衣 凉 背心',
 '我不 高手 呦']

In [14]:
# Split data into training, testing sets & validation sets 
Train_texts, Test_texts, Train_labels, Test_labels = train_test_split(
    comments, train[target_labels].values, test_size=0.3, random_state=50)

#validation set
test_texts, val_texts, test_labels, val_labels = train_test_split(
    Test_texts, Test_labels, test_size=0.32, random_state=23)

print('Training Dataset -->',len(Train_texts), Train_labels.shape)
print('Testing Dataset -->',len(test_texts), test_labels.shape)
print('validation Dataset -->',len(val_texts), val_labels.shape)

Training Dataset --> 18200 (18200, 8)
Testing Dataset --> 5304 (5304, 8)
validation Dataset --> 2496 (2496, 8)


In [15]:
def tokenize_and_encode(tokenizer, comments, labels, max_length=128):
    # Initialize empty lists to store tokenized inputs and attention masks
    input_ids = []
    attention_masks = []

    # Iterate through each comment in the 'comments' list
    for comment in comments:
        # Tokenize and encode the comment using the BERT tokenizer
        encoded_dict = tokenizer.encode_plus(
            comment,
            add_special_tokens=True,
            max_length=max_length,
            pad_to_max_length=True,
            return_attention_mask=True,
            return_tensors='pt'
        )

        # Append the tokenized input and attention mask to their respective lists
        input_ids.append(encoded_dict['input_ids'])
        attention_masks.append(encoded_dict['attention_mask'])

    # Convert the lists of tokenized inputs and attention masks to PyTorch tensors
    input_ids = torch.cat(input_ids, dim=0)
    attention_masks = torch.cat(attention_masks, dim=0)

    # Convert the labels to a PyTorch tensor with the data type float32
    labels = torch.tensor(labels, dtype=torch.float32)

    # Return the tokenized inputs, attention masks, and labels as PyTorch tensors
    return input_ids, attention_masks, labels

In [45]:
# comments_test
input_ids_test, attention_masks_test, labels = tokenize_and_encode(
    tokenizer, 
    comments_test, 
    []
)
input_ids_test, attention_masks_test

(tensor([[ 101, 1921, 1525,  ...,    0,    0,    0],
         [ 101, 4696, 3301,  ...,    0,    0,    0],
         [ 101, 4696, 4638,  ...,    0,    0,    0],
         ...,
         [ 101, 1777,  678,  ...,    0,    0,    0],
         [ 101, 1348, 1453,  ...,    0,    0,    0],
         [ 101, 1157, 2458,  ...,    0,    0,    0]]),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]))

In [16]:
# Token Initialization
tokenizer = BertTokenizer.from_pretrained('./model/bert-base-chinese', do_lower_case=True)

# Model Initialization
model = BertForSequenceClassification.from_pretrained('./model/bert-base-chinese', num_labels=8, ignore_mismatched_sizes=True,)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at ./model/bert-base-chinese and are newly initialized because the shapes did not match:
- classifier.weight: found shape torch.Size([7, 768]) in the checkpoint and torch.Size([8, 768]) in the model instantiated
- classifier.bias: found shape torch.Size([7]) in the checkpoint and torch.Size([8]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [17]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(21128, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, element

In [18]:
# Move model to GPU if available
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(device)

model =model.to(device)

cuda


In [19]:
# Tokenize and Encode the comments and labels for the training set
input_ids, attention_masks, labels = tokenize_and_encode(
    tokenizer, 
    Train_texts, 
    Train_labels
)

# Step 4: Tokenize and Encode the comments and labels for the test set
test_input_ids, test_attention_masks, test_labels = tokenize_and_encode(
    tokenizer,
    test_texts,
    test_labels
)

# Tokenize and Encode the comments and labels for the validation set
val_input_ids, val_attention_masks, val_labels = tokenize_and_encode(
    tokenizer,
    val_texts,
    val_labels
)

print('Training Comments :',len(Train_texts))
print('Input Ids         :',input_ids.shape)
print('Attention Mask    :',attention_masks.shape)
print('Labels            :',labels.shape)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Training Comments : 18200
Input Ids         : torch.Size([18200, 128])
Attention Mask    : torch.Size([18200, 128])
Labels            : torch.Size([18200, 8])


In [20]:
k = 523
print('Training Comments -->>',Train_texts[k])
print('\nInput Ids -->>\n',input_ids[k])
print('\nDecoded Ids -->>\n',tokenizer.decode(input_ids[k]))
print('\nAttention Mask -->>\n',attention_masks[k])
print('\nLabels -->>',labels[k])

Training Comments -->> 这 消息 太 突然 太 叫 人 接受 不 不 说 好人 一生 平安 吗

Input Ids -->>
 tensor([ 101, 6821, 3867, 2622, 1922, 4960, 4197, 1922, 1373,  782, 2970, 1358,
         679,  679, 6432, 1962,  782,  671, 4495, 2398, 2128, 1408,  102,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0])

Decoded Ids -->>
 [CLS] 这 消 息 太 突 然 太 叫 人 接 受 不 不 说 好 人 一 生 平 安 吗 

In [21]:
len(input_ids[k])

128

In [22]:
# Creating DataLoader for the balanced dataset
batch_size = 32
train_dataset = TensorDataset(input_ids, attention_masks, labels)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

#test
test_dataset = TensorDataset(test_input_ids, test_attention_masks, test_labels)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

#val
val_dataset = TensorDataset(val_input_ids, val_attention_masks, val_labels)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

In [23]:
len(train_dataset),len(train_dataset)/batch_size,len(test_dataset)/batch_size,len(val_dataset)/batch_size

(18200, 568.75, 165.75, 78.0)

In [24]:
print('Batch Size :',train_loader.batch_size)
Batch =next(iter(train_loader))
print('Each Input ids shape :',Batch[0].shape)
print('Input ids :\n',Batch[0][0])
print('Corresponding Decoded text:\n',tokenizer.decode(Batch[0][0]))
print('Corresponding Attention Mask :\n',Batch[1][0])
print('Corresponding Label:',Batch[2][0])

Batch Size : 32
Each Input ids shape : torch.Size([32, 128])
Input ids :
 tensor([ 101,  704, 1744,  837, 5320, 2157, 1072,  704, 1744, 2471, 6629, 2408,
        3793, 7028, 6228,  679, 6814, 2457,  865, 2399,  752, 2658,  102,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0])
Corresponding Decoded text:
 [CLS] 中 国 传 统 家 具 中 国 引 起 广 泛 重 视 不 过 廿 

In [25]:
# Optimizer setup
optimizer = AdamW(model.parameters(), lr=0.00002)

In [28]:
def train_model(model, train_loader, val_loader, optimizer, device, num_epochs):
    # Loop through the specified number of epochs
    for epoch in range(num_epochs):
        # Set the model to training mode
        model.train() 
        # Initialize total loss for the current epoch
        total_loss = 0  

        # Loop through the batches in the training data
        for batch in train_loader:
            input_ids, attention_mask, labels = [t.to(device) for t in batch]
            # print(len(input_ids),len(input_ids))

            optimizer.zero_grad()
            # if labels.size()[0] != batch_size:
            outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            total_loss += loss.item()

            loss.backward()
            optimizer.step()

        model.eval()  # Set the model to evaluation mode
        val_loss = 0

        # Disable gradient computation during validation
        with torch.no_grad():
            for batch in val_loader:
                input_ids, attention_mask, labels = [t.to(device) for t in batch]
                # if labels.size()[0] != batch_size:
                outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
                loss = outputs.loss
                val_loss += loss.item()

        # Print the average loss for the current epoch
        print(f'Epoch {epoch+1}, Training Loss: {total_loss/len(train_loader)}, Validation Loss: {val_loss/len(val_loader)}')

# Assuming you have 'train_loader' and 'val_loader' defined elsewhere
# Call the function to train the model
train_model(model, train_loader, val_loader, optimizer, device, num_epochs=20)

Epoch 1, Training Loss: 0.18121593306741313, Validation Loss: 0.2747217573416539
Epoch 2, Training Loss: 0.14439380598403448, Validation Loss: 0.28969834993282956
Epoch 3, Training Loss: 0.11303724463773737, Validation Loss: 0.3204476489470555
Epoch 4, Training Loss: 0.08693034916801905, Validation Loss: 0.34964302755319154
Epoch 5, Training Loss: 0.06913524469678242, Validation Loss: 0.3933856447155659
Epoch 6, Training Loss: 0.05371765102470958, Validation Loss: 0.4004038159663861
Epoch 7, Training Loss: 0.04434959989807099, Validation Loss: 0.431045800447464
Epoch 8, Training Loss: 0.03595339406530499, Validation Loss: 0.45247360605459946
Epoch 9, Training Loss: 0.03199982963770837, Validation Loss: 0.4755172523168417
Epoch 10, Training Loss: 0.02833502842211582, Validation Loss: 0.4889264903389491
Epoch 11, Training Loss: 0.025482095729703697, Validation Loss: 0.5068318710113183
Epoch 12, Training Loss: 0.022392986091884975, Validation Loss: 0.519519376831177
Epoch 13, Training Los

In [29]:
#Evaluate the Model
def evaluate_model(model, test_loader, device):
    model.eval()  # Set the model to evaluation mode

    true_labels = []
    predicted_probs = []

    with torch.no_grad():
        for batch in test_loader:
            input_ids, attention_mask, labels = [t.to(device) for t in batch]

            # Get model's predictions
            outputs = model(input_ids, attention_mask=attention_mask)
            predicted_probs_batch = torch.sigmoid(outputs.logits)  # Use sigmoid for multilabel classification
            predicted_probs.append(predicted_probs_batch.cpu().numpy())

            true_labels_batch = labels.cpu().numpy()
            true_labels.append(true_labels_batch)

    # Combine predictions and labels for evaluation
    true_labels = np.concatenate(true_labels, axis=0)
    predicted_probs = np.concatenate(predicted_probs, axis=0)
    predicted_labels = (predicted_probs > 0.5).astype(int)  # Apply threshold for binary classification

    # Calculate evaluation metrics
    accuracy = accuracy_score(true_labels, predicted_labels)
    precision = precision_score(true_labels, predicted_labels, average='micro')
    recall = recall_score(true_labels, predicted_labels, average='micro')

    # Print the evaluation metrics
    print(f'Accuracy: {accuracy:.4f}')
    print(f'Precision: {precision:.4f}')
    print(f'Recall: {recall:.4f}')

# Call the function to evaluate the model on the test data
evaluate_model(model, test_loader, device)

Accuracy: 0.3963
Precision: 0.6863
Recall: 0.6481


In [30]:
# Save the tokenizer and model in the same directory
output_dir = "./Saved_model"
model.save_pretrained(output_dir)  # Save model's state dictionary and configuration
tokenizer.save_pretrained(output_dir)  # Save tokenizer's configuration and vocabulary

('./Saved_model/tokenizer_config.json',
 './Saved_model/special_tokens_map.json',
 './Saved_model/vocab.txt',
 './Saved_model/added_tokens.json')

In [50]:
import pandas as pd
path = '/root/data/'
test = pd.read_csv(path + 'test.csv',encoding='gb18030')
test

ID                                               Text
0        1                                 天 哪 她 还 真 以为 她 名画家
1        2    真 朋友 无功 利 心 真心 相待 ； 假 朋友 表面 上 逢迎 拍马 暗地里 下绊 子 使坏
2        3                              真的 好 累 好 累 想 休息 写下 文字
3        4                                 湿淋淋 头发 隔 着 毛衣 凉 背心
4        5                                            我不 高手 呦
...    ...                                                ...
6148  6149  再说 拐弯 让 直行 次 右 拐 同方向 直行 车 没有 走 完 我在 等待 后面 车 就 ...
6149  6150                                   这才 一个 学生 应有 面容 呀
6150  6151                        坐下 随着 这 声 命令 同学 们 七零八落 地 坐下
6151  6152  又 周末 去 城内 四 府 街 陈 老师 家里 送 代购 几 本 书 蒙 他 厚爱 再 赠 ...
6152  6153                               刚 开学 一星期 嗓子 就 已经 坏 掉

[6153 rows x 2 columns]

In [51]:
test = test.dropna()

In [52]:
comments_test=test['Text'].to_list()
comments_test[:5]

['天 哪 她 还 真 以为 她 名画家',
 '真 朋友 无功 利 心 真心 相待 ； 假 朋友 表面 上 逢迎 拍马 暗地里 下绊 子 使坏',
 '真的 好 累 好 累 想 休息 写下 文字',
 '湿淋淋 头发 隔 着 毛衣 凉 背心',
 '我不 高手 呦']

In [54]:
# comments_test
input_ids_test, attention_masks_test, labels = tokenize_and_encode(
    tokenizer, 
    comments_test, 
    []
)
input_ids_test, attention_masks_test

(tensor([[ 101, 1921, 1525,  ...,    0,    0,    0],
         [ 101, 4696, 3301,  ...,    0,    0,    0],
         [ 101, 4696, 4638,  ...,    0,    0,    0],
         ...,
         [ 101, 1777,  678,  ...,    0,    0,    0],
         [ 101, 1348, 1453,  ...,    0,    0,    0],
         [ 101, 1157, 2458,  ...,    0,    0,    0]]),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]))

In [90]:
labels = torch.tensor([1]).unsqueeze(0)
test_dataset = TensorDataset(input_ids_test, attention_masks_test)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True)

In [91]:
len(test_loader)

193

In [92]:
labels

tensor([[1]])

In [93]:
model.eval()  # Set the model to evaluation mode
true_labels = []
predicted_probs = []
predicted_probs

[]

In [95]:
i=0
with torch.no_grad():
        for batch in test_loader:
            input_ids, attention_mask = [t.to(device) for t in batch]
            i=i+1
            # print(input_ids.size())

            # Get model's predictions
            outputs = model(input_ids, attention_mask=attention_mask)
            predicted_probs_batch = torch.sigmoid(outputs.logits)  # Use sigmoid for multilabel classification
            predicted_probs.append(predicted_probs_batch.cpu().numpy())


# Combine predictions and labels for evaluation
predicted_probs = np.concatenate(predicted_probs, axis=0)
predicted_labels = (predicted_probs > 0.5).astype(int)  # Apply threshold for binary classification

In [97]:
predicted_labels

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [99]:
predicted_labels = pd.DataFrame(predicted_labels)
predicted_labels

0  1  2  3  4  5  6  7
0     0  0  1  0  0  0  0  0
1     0  0  1  0  0  0  0  0
2     1  1  0  0  0  0  0  0
3     1  1  0  1  0  0  0  0
4     0  0  0  0  0  0  1  0
...  .. .. .. .. .. .. .. ..
6148  0  0  0  0  0  1  0  0
6149  0  0  1  0  0  1  0  0
6150  0  0  0  0  1  1  0  0
6151  0  1  0  0  0  0  0  0
6152  0  1  0  0  0  0  0  0

[6153 rows x 8 columns]

In [102]:
predicted_labels.columns = target_labels
# predicted_labels = predicted_labels.rename(columns={'0':'Anger', '1':'Anxiety', '2':'Expect','3':'Hate', '4':'Joy', '5':'Love', '6':'Sorrow','7':'Surprise'})
predicted_labels

Anger  Anxiety  Expect  Hate  Joy  Love  Sorrow  Surprise
0         0        0       1     0    0     0       0         0
1         0        0       1     0    0     0       0         0
2         1        1       0     0    0     0       0         0
3         1        1       0     1    0     0       0         0
4         0        0       0     0    0     0       1         0
...     ...      ...     ...   ...  ...   ...     ...       ...
6148      0        0       0     0    0     1       0         0
6149      0        0       1     0    0     1       0         0
6150      0        0       0     0    1     1       0         0
6151      0        1       0     0    0     0       0         0
6152      0        1       0     0    0     0       0         0

[6153 rows x 8 columns]

In [105]:
# test['ID'].join(predicted_labels)
test1 = pd.concat([test,predicted_labels], axis=1)
test1

ID                                               Text  Anger  Anxiety  \
0        1                                 天 哪 她 还 真 以为 她 名画家      0        0   
1        2    真 朋友 无功 利 心 真心 相待 ； 假 朋友 表面 上 逢迎 拍马 暗地里 下绊 子 使坏      0        0   
2        3                              真的 好 累 好 累 想 休息 写下 文字      1        1   
3        4                                 湿淋淋 头发 隔 着 毛衣 凉 背心      1        1   
4        5                                            我不 高手 呦      0        0   
...    ...                                                ...    ...      ...   
6148  6149  再说 拐弯 让 直行 次 右 拐 同方向 直行 车 没有 走 完 我在 等待 后面 车 就 ...      0        0   
6149  6150                                   这才 一个 学生 应有 面容 呀      0        0   
6150  6151                        坐下 随着 这 声 命令 同学 们 七零八落 地 坐下      0        0   
6151  6152  又 周末 去 城内 四 府 街 陈 老师 家里 送 代购 几 本 书 蒙 他 厚爱 再 赠 ...      0        1   
6152  6153                               刚 开学 一星期 嗓子 就 已经 坏 掉      0        1   

      Expect  Hate  Joy  Love  Sorrow  Surprise  
0          1     0    0     0       0         0  
1          1     0    0     0       0         0  
2          0     0    0     0       0         0  
3          0     1    0     0       0         0  
4          0     0    0     0       1         0  
...      ...   ...  ...   ...     ...       ...  
6148       0     0    0     1       0         0  
6149       1     0    0     1       0         0  
6150       0     0    1     1       0         0  
6151       0     0    0     0       0         0  
6152       0     0    0     0       0         0  

[6153 rows x 10 columns]

In [108]:
test1.to_csv('./test1.csv')

In [76]:
import pandas as pd
test = pd.read_csv('./test1.csv')
test = test.drop('Text',axis=1)
test

Unnamed: 0    ID  Anger  Anxiety  Expect  Hate  Joy  Love  Sorrow  \
0              0     1      0        0       1     0    0     0       0   
1              1     2      0        0       1     0    0     0       0   
2              2     3      1        1       0     0    0     0       0   
3              3     4      1        1       0     1    0     0       0   
4              4     5      0        0       0     0    0     0       1   
...          ...   ...    ...      ...     ...   ...  ...   ...     ...   
6148        6148  6149      0        0       0     0    0     1       0   
6149        6149  6150      0        0       1     0    0     1       0   
6150        6150  6151      0        0       0     0    1     1       0   
6151        6151  6152      0        1       0     0    0     0       0   
6152        6152  6153      0        1       0     0    0     0       0   

      Surprise  
0            0  
1            0  
2            0  
3            0  
4            0  
...        ...  
6148         0  
6149         0  
6150         0  
6151         0  
6152         0  

[6153 rows x 10 columns]

In [77]:
test1 = test.loc[ : , "Anger":"Surprise"]
test1

Anger  Anxiety  Expect  Hate  Joy  Love  Sorrow  Surprise
0         0        0       1     0    0     0       0         0
1         0        0       1     0    0     0       0         0
2         1        1       0     0    0     0       0         0
3         1        1       0     1    0     0       0         0
4         0        0       0     0    0     0       1         0
...     ...      ...     ...   ...  ...   ...     ...       ...
6148      0        0       0     0    0     1       0         0
6149      0        0       1     0    0     1       0         0
6150      0        0       0     0    1     1       0         0
6151      0        1       0     0    0     0       0         0
6152      0        1       0     0    0     0       0         0

[6153 rows x 8 columns]

In [78]:
dict(test1.iloc[0])

{'Anger': 0,
 'Anxiety': 0,
 'Expect': 1,
 'Hate': 0,
 'Joy': 0,
 'Love': 0,
 'Sorrow': 0,
 'Surprise': 0}

In [79]:
# 根据值来查找键
def get_keys(d, value):
    return ["'" + k + "'" for k, v in d.items() if v == value]

# keys = []
# 找出值为2的键
keys = get_keys(dict(test1.iloc[2]), 1)
keys

["'Anger'", "'Anxiety'"]

In [80]:
df = test1.apply(lambda x: get_keys(dict(x), 1), axis=1)
df

0                         ['Expect']
1                         ['Expect']
2               ['Anger', 'Anxiety']
3       ['Anger', 'Anxiety', 'Hate']
4                         ['Sorrow']
                    ...             
6148                        ['Love']
6149              ['Expect', 'Love']
6150                 ['Joy', 'Love']
6151                     ['Anxiety']
6152                     ['Anxiety']
Length: 6153, dtype: object

In [83]:
test2 = pd.concat([test['ID'],df], axis=1)
test2.columns=['ID','Labels']


In [85]:
test2.to_csv('./test2.csv')

In [7]:
# !pip install -i https://pypi.tuna.tsinghua.edu.cn/simple transformers

# import transformers

In [47]:
# !pip install pytorch-pretrained-bert

Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple
     |████████████████████████████████| 123 kB 1.3 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 64.4 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 47.4 MB/s eta 0:00:01
     |████████████████████████████████| 11.3 MB 16.4 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 13.5 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 38.8 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 41.1 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 42.7 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 39.3 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 83.6 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 64.7 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 63.3 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 77.6 MB/s eta 0:00:01
     |█████████████████████████

In [4]:
# from transformers import BertTokenizer, BertModel
# tokenizer = BertTokenizer.from_pretrained("./model/bert-base-chinese")
# model = BertModel.from_pretrained("./model/bert-base-chinese")

# # ...一系列操作
# text = "Replace me by any text you'd like."
# encoded_input = tokenizer(text, return_tensors='pt')
# output = model(**encoded_input)
# print(output)


BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.8765,  0.0977, -0.3460,  ...,  0.5527,  0.0241, -0.2857],
         [-0.8829,  0.2881,  0.0876,  ...,  0.2261, -0.3675, -0.3354],
         [-0.3034,  0.3377,  0.6217,  ..., -0.3015,  0.2828,  0.0967],
         ...,
         [ 0.6289,  0.0569, -0.0327,  ...,  0.2157, -0.4363, -0.1250],
         [ 0.0912,  0.2132, -0.7634,  ...,  0.0302, -0.1138,  0.2884],
         [-0.5577, -0.4237, -0.1272,  ...,  0.1528, -0.1279,  0.1162]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[ 0.9995,  1.0000,  0.9949,  0.8371,  0.5831,  0.5679, -0.4190, -0.9272,
          0.9958, -0.9588,  1.0000,  0.9994, -0.0425, -0.9962,  0.9999, -0.9988,
         -0.9984,  0.9786,  0.9971, -0.1568,  0.9998, -1.0000, -0.9813, -0.5638,
         -0.1753,  0.9740,  0.8660, -0.0171, -0.9998,  0.9819,  0.9332,  0.9991,
          0.9558, -0.9999, -0.9920, -0.3774, -0.3995,  0.9865, -0.7910, -0.7119,
         -0.9659, -0.6644, -0.42

In [15]:
# !pip install seaborn

In [16]:
# !pip install plotly

In [17]:
# !pip install wordcloud

In [18]:
# !pip install scikit-learn
# import scikit-learn

In [19]:
# import transformers